### ISSUE TITLE
/issue/archive is empty

### ISSUE THREAD

**Issue by josuevalrob** [Vitaliy-1/oldGregg#53]
Hello!. 
When I try to go to `/issue/archive` it show me an empty page. How can I fix this?.  
I dont have any console log message. 
I can perfectly see the different articles individualy. 
PD: Beautifull theme!. Very useful.

**Comment by anupent** [comment]
Same for me too.

**Comment by Vitaliy-1** [comment]
I have fixed it yesterday. The master release should be compliant with latest OJS.

**Comment by Vitaliy-1** [comment]
this commit actually: https://github.com/Vitaliy-1/oldGregg/commit/5f9c6be051c25aa5b51974b85facbd6b5dea848b

**Comment by EduardoOsquel** [comment]
Vitaly-1, how you fixed this error? I need help

**Comment by EduardoOsquel** [comment]
@Vitaliy-1 I see how to fix it, thanks...

**Comment by josuevalrob** [comment]
how? I have the last relase, but the problem still there... 
[Issue/archive](http://5.56.56.37/old_gregg/index.php/ingenieria-civil/issue/archive)

**Comment by EduardoOsquel** [comment]
@josuevalrob Why is the oldGregg folder out of plugins/themes folders?

**Comment by josuevalrob** [comment]
Is inside of it, like it is recommended: 
**How to use**

1. Download the plugin.
2. Rename directory to the oldGregg.
3. Copy to themes directory inside OJS.

**Comment by EduardoOsquel** [comment]
in this error log file [Newsletter\old_gregg\lib\pkp\lib\vendor\smarty\smarty\libs\Smarty.class.php] the folder location seems to be wrong! must be like this [ojs_directory/plugins/themes/oldGregg] check for this please!

**Comment by josuevalrob** [comment]
Sorry if this is a silly question but. 
Which folder should I put inside my oldGregg theme? the vendor folder? or the smarty folder? @EduardoOsquel

**Comment by EduardoOsquel** [comment]
must be like this [ojs_directory/plugins/themes/oldGregg]...

**Comment by josuevalrob** [comment]
Yeah, this is how I have it: 

> C:\inetpub\wwwroot\Newsletter\old_gregg\plugins\themes\oldGregg

My theme Site name is ols_gregg and my theme name is oldGregg

Sorry for the confusion. 

I don't know why it is giving me errors from my OJS root folders, **I will test with a fresh installation**, maybe I touch something there...

**Comment by EduardoOsquel** [comment]
@josuevalrob  Ohhhhhh sorry... if you got the same issue, try this:

https://github.com/Vitaliy-1/oldGregg/commit/5f9c6be051c25aa5b51974b85facbd6b5dea848b#diff-a1ed6d61c23c3df405232fd4b17b91aeR12

**Comment by josuevalrob** [comment]
thanks, I will try that tomorrow... btw, i have the last version of OldGregg.

**Comment by josuevalrob** [comment]
Was a problem from my OJS core.

**Comment by mayolag** [comment]
I'm having the same problem too, I'm using the 1.1.0.1 version because I have OJS 3.1.1. (I was unable to upgrade it). Please help!
